# # name: smart_park_assist
# # description: "A new Flutter project."
# # publish_to: 'none'  # Uncomment this line if you wish to keep the package private.

# # # The following defines the version and build number for your application.
# # version: 1.0.0+1

# # environment:
# #   sdk: ^3.5.2

# # dependencies:
# #   flutter:
# #     sdk: flutter
# #   video_player: ^2.3.0  # Ensure this is the correct version
# #   cupertino_icons: ^1.0.8
# #   intl: ^0.20.0  # Add the intl package for date and time formatting
# #   http: ^1.2.2
# #   shared_preferences: ^2.0.15  # Ensure this is the latest version
# #   mqtt_client: ^10.5.1
# #   logger: ^2.5.0
# #   uuid: ^3.0.6
# #   animated_text_kit: ^4.2.1  # Add this dependency
# #   font_awesome_flutter: ^10.0.0  # Add this dependency
# #   page_transition: ^2.0.0  # Add this dependency

# # dev_dependencies:
# #   flutter_test:
# #     sdk: flutter
# #   flutter_lints: ^5.0.0

# # flutter:
# #   uses-material-design: true

# #   # To add assets to your application, add an assets section, like this:
# #   assets:
# #     - images/
# #     - images/videos/  # Ensure this directory exists and contains your video file

# #   # The following section is for adding custom fonts (if needed)
# #   # fonts:
# #   #   - family: Schyler
# #   #     fonts:
# #   #       - asset: fonts/Schyler-Regular.ttf
# #   #       - asset: fonts/Schyler-Italic.ttf
# #   #         style: italic
# #   #   - family: Trajan Pro
# #   #     fonts:
# #   #       - asset: fonts/TrajanPro.ttf
# #   #       - asset: fonts/TrajanPro_Bold.ttf
# #   #         weight: 700


# name: smart_park_assist
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ^3.5.2

# dependencies:
#   flutter:
#     sdk: flutter
#   video_player: ^2.3.0
#   cupertino_icons: ^1.0.8
#   intl: ^0.20.0
#   http: ^1.2.2
#   shared_preferences: ^2.0.15
#   mqtt_client: ^10.5.1
#   logger: ^2.5.0
#   uuid: ^3.0.6
#   animated_text_kit: ^4.2.1
#   font_awesome_flutter: ^10.0.0
#   page_transition: ^2.0.0
#   image_picker: ^1.0.4   # ✅ Added here

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true

#   assets:
#     - images/
#     - images/videos/


# name: smart_park_assist
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ^3.5.2

# dependencies:
#   flutter:
#     sdk: flutter
#   video_player: ^2.3.0
#   cupertino_icons: ^1.0.8
#   intl: ^0.20.0
#   http: ^1.2.2
#   shared_preferences: ^2.0.15
#   mqtt_client: ^10.5.1
#   logger: ^2.5.0
#   uuid: ^3.0.6
#   animated_text_kit: ^4.2.1
#   font_awesome_flutter: ^10.5.0  # ✅ updated version
#   page_transition: ^2.0.0
#   image_picker: ^1.0.4
#   url_launcher: ^6.2.1           # ✅ newly added

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true

#   assets:
#     - images/
#     - images/videos/




name: smart_park_assist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.3.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.0
  http: ^1.2.2
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  mqtt_client: ^10.5.1
  logger: ^2.5.0
  uuid: ^3.0.6
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.5.0  # Updated version
  page_transition: ^2.0.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.8  # Corrected indentation
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  sqflite: ^2.0.0+4
  path: ^1.7.0
  syncfusion_flutter_gauges: ^29.1.39
  loading_indicator: ^3.0.3
  
  

         

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/videos/
